# Generated by Django 4.1 on 2023-12-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('agendaid', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.TextField()),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('attendeeid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField()),
            ],
            options={
                'db_table': 'attendee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meetingid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateField()),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meetingresource',
            fields=[
                ('meetingresourceid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'meetingresource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField()),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resourceid', models.AutoField(primary_key=True, serialize=False)),
                ('resourcename', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('password', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_cast', models.DateTimeField()),
                ('candidate', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'votes',
                'managed': False,
            },
        ),
    ]
